### ISSUE TITLE
[Docs] Convert Java code to Kotlin

### ISSUE THREAD

**Issue by Lee-Soyeon** [DahamChoi/SilverWalk#4]
## Description

* We are all **Java developers**. However, the project was decided to develop into Kotlin. Because of **readability** and **stability**.
* This document summarizes _the challenges that arose in the process of converting Java to Kotlin_ and _how the issues were addressed_ and _what decisions were made_.

## Progress

- [x] Create Kotlin Project
- [x] Learn the Kotlin Language

## References

[Develop Android apps with Kotlin](https://developer.android.com/kotlin/first)
[[Kotlin] 코틀린이란?](https://tourspace.tistory.com/61)
[자바로 작성된 안드로이드 앱을 코틀린으로 변환하고 난 후 느낀점 정리](https://medium.com/@zerodice0/java%EB%A1%9C-%EC%9E%91%EC%84%B1%EB%90%9C-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EC%95%B1%EC%9D%84-kotlin%EC%9C%BC%EB%A1%9C-%EB%B3%80%ED%99%98%ED%95%98%EA%B3%A0-%EB%82%9C-%ED%9B%84-%EB%8A%90%EB%82%80%EC%A0%90-%EC%A0%95%EB%A6%AC-121d0c441b05)

**Comment by DahamChoi** [comment]
If Use apply plugin: 'kotlin-android-extensions'
We don't need findViewById()!
We can access the view to use viewId

**Comment by DahamChoi** [comment]
Kotlin don't have static parameter
[Kotlin: Object Declaration, 그리고 Companion Object](https://medium.com/@lunay0ung/kotlin-object-declaration-%EA%B7%B8%EB%A6%AC%EA%B3%A0-companion-object-feat-static-d5c97c21168)

**Comment by DahamChoi** [comment]
Kotlin don't have Ternary operator
javaStyle
currentMissionIndex = (currentMissionIndex == 0) ? 4 : currentMissionIndex - 1
KotlinStyle
currentMissionIndex = if (currentMissionIndex == 0) 4 else currentMissionIndex - 1

**Comment by DahamChoi** [comment]
Kotlin Power!
**Java**
```
public float convertDpToPixel(float dp){
    Resources resources = this.getResources();
    DisplayMetrics metrics = resources.getDisplayMetrics();
    float px = dp * ((float)metrics.densityDpi / DisplayMetrics.DENSITY_DEFAULT);
    return px;
}
```

**Kotlin**
```
fun convertDpToPixel(dp : Float) : Float {
        return dp * (resources.displayMetrics.densityDpi.toFloat() / DisplayMetrics.DENSITY_DEFAULT)
    }
```
